import Foundation

enum SportCatalog {
    static let items: [SportCatalogItem] = [
        SportCatalogItem(
            activity: .walking,
            displayName: "Brisk Walking",
            allowedEnvironments: [.indoor, .outdoor, .both],
            requiredEquipments: [.none],
            contraindicatedConditions: [],
            contraindicatedInjuries: [],
            impactLevel: .low,
            defaultDurationRangeMinutes: 20...50,
            minRPE: 2,
            maxRPE: 5,
            baseCardioScore: 82,
            shortDescription: "Low-impact aerobic base builder."
        ),
        SportCatalogItem(
            activity: .inclineWalking,
            displayName: "Incline Walking",
            allowedEnvironments: [.indoor, .outdoor, .both],
            requiredEquipments: [.treadmill, .none],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.kneePain, .multipleIssues],
            impactLevel: .moderate,
            defaultDurationRangeMinutes: 15...40,
            minRPE: 3,
            maxRPE: 6,
            baseCardioScore: 84,
            shortDescription: "Higher cardio stimulus while remaining low-impact."
        ),
        SportCatalogItem(
            activity: .nordicWalking,
            displayName: "Nordic Walking",
            allowedEnvironments: [.outdoor, .both],
            requiredEquipments: [.none],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.shoulderIssue, .multipleIssues],
            impactLevel: .low,
            defaultDurationRangeMinutes: 20...50,
            minRPE: 3,
            maxRPE: 5,
            baseCardioScore: 83,
            shortDescription: "Full-body walking variation with moderate cardio demand."
        ),
        SportCatalogItem(
            activity: .lightJogging,
            displayName: "Light Jogging",
            allowedEnvironments: [.outdoor, .indoor, .both],
            requiredEquipments: [.none],
            contraindicatedConditions: [.jointProblems, .heartDisease, .arrhythmia, .asthma, .chronicRespiratoryCondition, .postSurgeryRecovery, .otherMedicalCondition],
            contraindicatedInjuries: [.kneePain, .backPain, .multipleIssues],
            impactLevel: .high,
            defaultDurationRangeMinutes: 15...35,
            minRPE: 4,
            maxRPE: 6,
            baseCardioScore: 83,
            shortDescription: "Progressive aerobic option with higher impact."
        ),
        SportCatalogItem(
            activity: .runWalkInterval,
            displayName: "Run-Walk Interval",
            allowedEnvironments: [.outdoor, .indoor, .both],
            requiredEquipments: [.none],
            contraindicatedConditions: [.heartDisease, .highBloodPressure, .asthma, .chronicRespiratoryCondition, .arrhythmia, .postSurgeryRecovery, .otherMedicalCondition],
            contraindicatedInjuries: [.kneePain, .backPain, .multipleIssues],
            impactLevel: .high,
            defaultDurationRangeMinutes: 12...30,
            minRPE: 4,
            maxRPE: 6,
            baseCardioScore: 85,
            shortDescription: "Interval cardio for controlled conditioning progression."
        ),
        SportCatalogItem(
            activity: .cycling,
            displayName: "Outdoor Cycling",
            allowedEnvironments: [.outdoor, .both],
            requiredEquipments: [.bicycle],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.multipleIssues],
            impactLevel: .low,
            defaultDurationRangeMinutes: 20...55,
            minRPE: 3,
            maxRPE: 6,
            baseCardioScore: 86,
            shortDescription: "Joint-friendly aerobic conditioning outdoors."
        ),
        SportCatalogItem(
            activity: .indoorCycling,
            displayName: "Indoor Cycling",
            allowedEnvironments: [.indoor, .both],
            requiredEquipments: [.bicycle, .gymMembership],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.multipleIssues],
            impactLevel: .low,
            defaultDurationRangeMinutes: 15...45,
            minRPE: 3,
            maxRPE: 6,
            baseCardioScore: 85,
            shortDescription: "Steady cardio with controlled indoor intensity."
        ),
        SportCatalogItem(
            activity: .swimming,
            displayName: "Swimming",
            allowedEnvironments: [.indoor, .both],
            requiredEquipments: [.swimmingPoolAccess, .gymMembership],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.shoulderIssue, .multipleIssues],
            impactLevel: .low,
            defaultDurationRangeMinutes: 20...45,
            minRPE: 3,
            maxRPE: 6,
            baseCardioScore: 88,
            shortDescription: "Full-body low-impact cardiovascular training."
        ),
        SportCatalogItem(
            activity: .aquaAerobics,
            displayName: "Aqua Aerobics",
            allowedEnvironments: [.indoor, .both],
            requiredEquipments: [.swimmingPoolAccess, .gymMembership],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.shoulderIssue, .multipleIssues],
            impactLevel: .low,
            defaultDurationRangeMinutes: 20...45,
            minRPE: 2,
            maxRPE: 5,
            baseCardioScore: 76,
            shortDescription: "Water-based cardio with reduced joint loading."
        ),
        SportCatalogItem(
            activity: .hiking,
            displayName: "Hiking",
            allowedEnvironments: [.outdoor, .both],
            requiredEquipments: [.none],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.kneePain, .multipleIssues],
            impactLevel: .moderate,
            defaultDurationRangeMinutes: 30...70,
            minRPE: 3,
            maxRPE: 6,
            baseCardioScore: 80,
            shortDescription: "Sustained aerobic effort on variable terrain."
        ),
        SportCatalogItem(
            activity: .stairClimbing,
            displayName: "Stair Climbing",
            allowedEnvironments: [.indoor, .outdoor, .both],
            requiredEquipments: [.none, .stairsOrHillAccess, .gymMembership],
            contraindicatedConditions: [.heartDisease, .highBloodPressure, .arrhythmia, .chronicRespiratoryCondition, .postSurgeryRecovery, .otherMedicalCondition],
            contraindicatedInjuries: [.kneePain, .multipleIssues],
            impactLevel: .high,
            defaultDurationRangeMinutes: 10...25,
            minRPE: 4,
            maxRPE: 6,
            baseCardioScore: 84,
            shortDescription: "Short-duration high-cardio option."
        ),
        SportCatalogItem(
            activity: .ellipticalTrainer,
            displayName: "Elliptical Trainer",
            allowedEnvironments: [.indoor, .both],
            requiredEquipments: [.ellipticalMachine, .gymMembership],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.multipleIssues],
            impactLevel: .low,
            defaultDurationRangeMinutes: 15...40,
            minRPE: 3,
            maxRPE: 6,
            baseCardioScore: 81,
            shortDescription: "Low-impact machine cardio with stable load."
        ),
        SportCatalogItem(
            activity: .rowing,
            displayName: "Rowing Ergometer",
            allowedEnvironments: [.indoor, .both],
            requiredEquipments: [.rowingMachine, .gymMembership],
            contraindicatedConditions: [.heartDisease, .highBloodPressure, .arrhythmia, .chronicRespiratoryCondition, .postSurgeryRecovery, .otherMedicalCondition],
            contraindicatedInjuries: [.backPain, .shoulderIssue, .multipleIssues],
            impactLevel: .moderate,
            defaultDurationRangeMinutes: 12...30,
            minRPE: 4,
            maxRPE: 6,
            baseCardioScore: 84,
            shortDescription: "Full-body cardio with moderate-to-high effort."
        ),
        SportCatalogItem(
            activity: .dancing,
            displayName: "Dance Cardio",
            allowedEnvironments: [.indoor, .both],
            requiredEquipments: [.none],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.kneePain, .multipleIssues],
            impactLevel: .moderate,
            defaultDurationRangeMinutes: 15...40,
            minRPE: 3,
            maxRPE: 6,
            baseCardioScore: 78,
            shortDescription: "Enjoyable rhythmic cardio with good adherence."
        ),
        SportCatalogItem(
            activity: .lowImpactAerobics,
            displayName: "Low-Impact Aerobics",
            allowedEnvironments: [.indoor, .both],
            requiredEquipments: [.none],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.multipleIssues],
            impactLevel: .low,
            defaultDurationRangeMinutes: 15...35,
            minRPE: 3,
            maxRPE: 5,
            baseCardioScore: 75,
            shortDescription: "Steady aerobic training with reduced impact."
        ),
        SportCatalogItem(
            activity: .yoga,
            displayName: "Vinyasa Yoga",
            allowedEnvironments: [.indoor, .both],
            requiredEquipments: [.yogaMat],
            contraindicatedConditions: [],
            contraindicatedInjuries: [.multipleIssues],
            impactLevel: .low,
            defaultDurationRangeMinutes: 15...45,
            minRPE: 2,
            maxRPE: 4,
            baseCardioScore: 67,
            shortDescription: "Cardio-light flow with stress-regulation benefits."
        ),
        SportCatalogItem(
            activity: .stretching,
            displayName: "Dynamic Stretching Flow",
            allowedEnvironments: [.indoor, .outdoor, .both],
            requiredEquipments: [.none],
            contraindicatedConditions: [],
            contraindicatedInjuries: [],
            impactLevel: .low,
            defaultDurationRangeMinutes: 10...25,
            minRPE: 2,
            maxRPE: 3,
            baseCardioScore: 55,
            shortDescription: "Mobility and active recovery support."
        ),
        SportCatalogItem(
            activity: .bodyweightExercise,
            displayName: "Bodyweight Cardio Circuit",
            allowedEnvironments: [.indoor, .outdoor, .both],
            requiredEquipments: [.none],
            contraindicatedConditions: [.heartDisease, .highBloodPressure, .arrhythmia, .chronicRespiratoryCondition, .postSurgeryRecovery, .otherMedicalCondition],
            contraindicatedInjuries: [.backPain, .multipleIssues],
            impactLevel: .moderate,
            defaultDurationRangeMinutes: 12...30,
            minRPE: 4,
            maxRPE: 6,
            baseCardioScore: 74,
            shortDescription: "Simple equipment-free conditioning circuits."
        ),
        SportCatalogItem(
            activity: .badminton,
            displayName: "Badminton (Recreational)",
            allowedEnvironments: [.indoor, .outdoor, .both],
            requiredEquipments: [.badmintonRacket, .sportsCourtAccess],
            contraindicatedConditions: [.heartDisease, .arrhythmia, .chronicRespiratoryCondition, .postSurgeryRecovery, .otherMedicalCondition],
            contraindicatedInjuries: [.kneePain, .shoulderIssue, .multipleIssues],
            impactLevel: .moderate,
            defaultDurationRangeMinutes: 20...45,
            minRPE: 4,
            maxRPE: 6,
            baseCardioScore: 79,
            shortDescription: "Intermittent cardio through rally movement."
        ),
        SportCatalogItem(
            activity: .tennisDoubles,
            displayName: "Tennis Doubles",
            allowedEnvironments: [.outdoor, .indoor, .both],
            requiredEquipments: [.tennisRacket, .sportsCourtAccess],
            contraindicatedConditions: [.heartDisease, .arrhythmia, .chronicRespiratoryCondition, .postSurgeryRecovery, .otherMedicalCondition],
            contraindicatedInjuries: [.kneePain, .shoulderIssue, .multipleIssues],
            impactLevel: .moderate,
            defaultDurationRangeMinutes: 25...55,
            minRPE: 4,
            maxRPE: 6,
            baseCardioScore: 81,
            shortDescription: "Moderate-intensity intermittent cardio gameplay."
        )
    ]
}
